package net.flamgop.vulkanic.core;

import net.flamgop.vulkanic.memory.VulkanicDeviceSize;
import net.flamgop.vulkanic.pipeline.graphics.VulkanicSampleCountFlag;
import net.flamgop.vulkanic.util.EnumIntBitset;
import org.joml.*;
import org.lwjgl.vulkan.VkPhysicalDeviceLimits;

public record VulkanicPhysicalDeviceLimits(
        int maxImageDimension1D,
        int maxImageDimension2D,
        int maxImageDimension3D,
        int maxImageDimensionCube,
        int maxImageArrayLayers,
        int maxTexelBufferElements,
        int maxUniformBufferRange,
        int maxStorageBufferRange,
        int maxPushConstantsSize,
        int maxMemoryAllocationCount,
        int maxSamplerAllocationCount,
        VulkanicDeviceSize bufferImageGranularity,
        VulkanicDeviceSize sparseAddressSpaceSize,
        int maxBoundDescriptorSets,
        int maxPerStageDescriptorSamplers,
        int maxPerStageDescriptorUniformBuffers,
        int maxPerStageDescriptorStorageBuffers,
        int maxPerStageDescriptorSampledImages,
        int maxPerStageDescriptorStorageImages,
        int maxPerStageDescriptorInputAttachments,
        int maxPerStageResources,
        int maxDescriptorSetSamplers,
        int maxDescriptorSetUniformBuffers,
        int maxDescriptorSetUniformBuffersDynamic,
        int maxDescriptorSetStorageBuffers,
        int maxDescriptorSetStorageBuffersDynamic,
        int maxDescriptorSetSampledImages,
        int maxDescriptorSetStorageImages,
        int maxDescriptorSetInputAttachments,
        int maxVertexInputAttributes,
        int maxVertexInputBindings,
        int maxVertexInputAttributeOffset,
        int maxVertexInputBindingStride,
        int maxVertexOutputComponents,
        int maxTessellationGenerationLevel,
        int maxTessellationPatchSize,
        int maxTessellationControlPerVertexInputComponents,
        int maxTessellationControlPerVertexOutputComponents,
        int maxTessellationControlPerPatchOutputComponents,
        int maxTessellationControlTotalOutputComponents,
        int maxTessellationEvaluationInputComponents,
        int maxTessellationEvaluationOutputComponents,
        int maxGeometryShaderInvocations,
        int maxGeometryInputComponents,
        int maxGeometryOutputComponents,
        int maxGeometryOutputVertices,
        int maxGeometryTotalOutputComponents,
        int maxFragmentInputComponents,
        int maxFragmentOutputAttachments,
        int maxFragmentDualSrcAttachments,
        int maxFragmentCombinedOutputResources,
        int maxComputeSharedMemorySize,
        Vector3ic maxComputeWorkGroupCount,
        int maxComputeWorkGroupInvocations,
        Vector3ic maxComputeWorkGroupSize,
        int subPixelPrecisionBits,
        int subTexelPrecisionBits,
        int mipmapPrecisionBits,
        int maxDrawIndexedIndexValue,
        int maxDrawIndirectCount,
        float maxSamplerLodBias,
        float maxSamplerAnisotropy,
        int maxViewports,
        Vector2ic maxViewportDimensions,
        Vector2fc viewportBoundsRange,
        int viewportSubPixelBits,
        long minMemoryMapAlignment,
        VulkanicDeviceSize minTexelBufferOffsetAlignment,
        VulkanicDeviceSize minUniformBufferOffsetAlignment,
        VulkanicDeviceSize minStorageBufferOffsetAlignment,
        int minTexelOffset,
        int maxTexelOffset,
        int minTexelGatherOffset,
        int maxTexelGatherOffset,
        float minInterpolationOffset,
        float maxInterpolationOffset,
        int subPixelInterpolationOffsetBits,
        int maxFramebufferWidth,
        int maxFramebufferHeight,
        int maxFramebufferLayers,
        EnumIntBitset<VulkanicSampleCountFlag> framebufferColorSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> framebufferDepthSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> framebufferStencilSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> framebufferNoAttachmentsSampleCounts,
        int maxColorAttachments,
        EnumIntBitset<VulkanicSampleCountFlag> sampledImageColorSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> sampledImageIntegerSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> sampledImageDepthSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> sampledImageStencilSampleCounts,
        EnumIntBitset<VulkanicSampleCountFlag> storageImageSampleCounts,
        int maxSampleMaskWords,
        boolean timestampComputeAndGraphics,
        float timestampPeriod,
        int maxClipDistances,
        int maxCullDistances,
        int maxCombinedClipAndCullDistances,
        int discreteQueuePriorities,
        Vector2fc pointSizeRange,
        Vector2fc lineWidthRange,
        float pointSizeGranularity,
        float lineWidthGranularity,
        boolean strictLines,
        boolean standardSampleLocations,
        VulkanicDeviceSize optimalBufferCopyOffsetAlignment,
        VulkanicDeviceSize optimalBufferCopyRowPitchAlignment,
        VulkanicDeviceSize nonCoherentAtomSize
) {
    public VulkanicPhysicalDeviceLimits(VkPhysicalDeviceLimits source) {
        this(
                source.maxImageDimension1D(),
                source.maxImageDimension2D(),
                source.maxImageDimension3D(),
                source.maxImageDimensionCube(),
                source.maxImageArrayLayers(),
                source.maxTexelBufferElements(),
                source.maxUniformBufferRange(),
                source.maxStorageBufferRange(),
                source.maxPushConstantsSize(),
                source.maxMemoryAllocationCount(),
                source.maxSamplerAllocationCount(),
                VulkanicDeviceSize.ofBytes(source.bufferImageGranularity()),
                VulkanicDeviceSize.ofBytes(source.sparseAddressSpaceSize()),
                source.maxBoundDescriptorSets(),
                source.maxPerStageDescriptorSamplers(),
                source.maxPerStageDescriptorUniformBuffers(),
                source.maxPerStageDescriptorStorageBuffers(),
                source.maxPerStageDescriptorSampledImages(),
                source.maxPerStageDescriptorStorageImages(),
                source.maxPerStageDescriptorInputAttachments(),
                source.maxPerStageResources(),
                source.maxDescriptorSetSamplers(),
                source.maxDescriptorSetUniformBuffers(),
                source.maxDescriptorSetUniformBuffersDynamic(),
                source.maxDescriptorSetStorageBuffers(),
                source.maxDescriptorSetStorageBuffersDynamic(),
                source.maxDescriptorSetSampledImages(),
                source.maxDescriptorSetStorageImages(),
                source.maxDescriptorSetInputAttachments(),
                source.maxVertexInputAttributes(),
                source.maxVertexInputBindings(),
                source.maxVertexInputAttributeOffset(),
                source.maxVertexInputBindingStride(),
                source.maxVertexOutputComponents(),
                source.maxTessellationGenerationLevel(),
                source.maxTessellationPatchSize(),
                source.maxTessellationControlPerVertexInputComponents(),
                source.maxTessellationControlPerVertexOutputComponents(),
                source.maxTessellationControlPerPatchOutputComponents(),
                source.maxTessellationControlTotalOutputComponents(),
                source.maxTessellationEvaluationInputComponents(),
                source.maxTessellationEvaluationOutputComponents(),
                source.maxGeometryShaderInvocations(),
                source.maxGeometryInputComponents(),
                source.maxGeometryOutputComponents(),
                source.maxGeometryOutputVertices(),
                source.maxGeometryTotalOutputComponents(),
                source.maxFragmentInputComponents(),
                source.maxFragmentOutputAttachments(),
                source.maxFragmentDualSrcAttachments(),
                source.maxFragmentCombinedOutputResources(),
                source.maxComputeSharedMemorySize(),
                new Vector3i(source.maxComputeWorkGroupCount()),
                source.maxComputeWorkGroupInvocations(),
                new Vector3i(source.maxComputeWorkGroupSize()),
                source.subPixelPrecisionBits(),
                source.subTexelPrecisionBits(),
                source.mipmapPrecisionBits(),
                source.maxDrawIndexedIndexValue(),
                source.maxDrawIndirectCount(),
                source.maxSamplerLodBias(),
                source.maxSamplerAnisotropy(),
                source.maxViewports(),
                new Vector2i(source.maxViewportDimensions()),
                new Vector2f(source.viewportBoundsRange()),
                source.viewportSubPixelBits(),
                source.minMemoryMapAlignment(),
                VulkanicDeviceSize.ofBytes(source.minTexelBufferOffsetAlignment()),
                VulkanicDeviceSize.ofBytes(source.minUniformBufferOffsetAlignment()),
                VulkanicDeviceSize.ofBytes(source.minStorageBufferOffsetAlignment()),
                source.minTexelOffset(),
                source.maxTexelOffset(),
                source.minTexelGatherOffset(),
                source.maxTexelGatherOffset(),
                source.minInterpolationOffset(),
                source.maxInterpolationOffset(),
                source.subPixelInterpolationOffsetBits(),
                source.maxFramebufferWidth(),
                source.maxFramebufferHeight(),
                source.maxFramebufferLayers(),
                new EnumIntBitset<>(source.framebufferColorSampleCounts()),
                new EnumIntBitset<>(source.framebufferDepthSampleCounts()),
                new EnumIntBitset<>(source.framebufferStencilSampleCounts()),
                new EnumIntBitset<>(source.framebufferNoAttachmentsSampleCounts()),
                source.maxColorAttachments(),
                new EnumIntBitset<>(source.sampledImageColorSampleCounts()),
                new EnumIntBitset<>(source.sampledImageIntegerSampleCounts()),
                new EnumIntBitset<>(source.sampledImageDepthSampleCounts()),
                new EnumIntBitset<>(source.sampledImageStencilSampleCounts()),
                new EnumIntBitset<>(source.storageImageSampleCounts()),
                source.maxSampleMaskWords(),
                source.timestampComputeAndGraphics(),
                source.timestampPeriod(),
                source.maxClipDistances(),
                source.maxCullDistances(),
                source.maxCombinedClipAndCullDistances(),
                source.discreteQueuePriorities(),
                new Vector2f(source.pointSizeRange()),
                new Vector2f(source.lineWidthRange()),
                source.pointSizeGranularity(),
                source.lineWidthGranularity(),
                source.strictLines(),
                source.standardSampleLocations(),
                VulkanicDeviceSize.ofBytes(source.optimalBufferCopyOffsetAlignment()),
                VulkanicDeviceSize.ofBytes(source.optimalBufferCopyRowPitchAlignment()),
                VulkanicDeviceSize.ofBytes(source.nonCoherentAtomSize())
        );
    }
}
